# Generated by Django 4.1 on 2023-09-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon_system_discount_alter_coupon_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
