# Generated by Django 4.1 on 2023-09-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon_coupon_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='system_discount',
        ),
    ]
