# Generated by Django 4.1 on 2023-09-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_cart_user_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
