# Generated by Django 4.1 on 2023-09-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='user',
        ),
    ]
