# Generated by Django 4.1 on 2023-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=5),
        ),
    ]
