# Generated by Django 4.1 on 2023-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_care',
            field=models.CharField(default='sgamare32@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.CharField(default='Please refer to the packaging of the product for expiry date.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fssai',
            field=models.CharField(default='1234567890', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='Saurabh Gamare Ventures LLP', max_length=50),
        ),
    ]
