# Generated by Django 4.1 on 2023-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_country_of_origin_product_customer_care_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='ECOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=20),
        ),
    ]
